Clean up action for merge
Signed-off-by: Ryan Cragun <me@ryan.ec>

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -10,6 +10,10 @@ author: 'Kyle Penfound <kpenfound@hashicorp.com>'
 # action description
 description: 'Packages binaries using nfpm.'
 
+branding:
+  icon: package
+  color: purple
+
 # action input values
 inputs:
   name:
@@ -105,15 +109,18 @@ runs:
     INPUT_POSTREMOVE: ${{ inputs.postremove }}
   steps:
     - uses: actions/checkout@v4
-    - id: Install nFPM
+      with:
+        path: nfpm_packaging
+    - name: Install nFPM
+      working-directory: nfpm_packaging
       shell: bash
       env:
         GH_TOKEN: ${{ github.token }}
       run: |
         VERSION=$(gh release list -R goreleaser/nfpm --exclude-drafts --exclude-pre-releases | grep ${{ inputs.nfpm_version }} | cut -f1)
 
-        mkdir -p $(dirname ${{ inputs.nfpm_destination }})
-        DESTINATION="$(readlink -f "${{ inputs.nfpm_destination }}")"
+        mkdir -p "$(dirname "${{ inputs.nfpm_destination }}")"
+        DESTINATION="$(readlink -f ${{ inputs.nfpm_destination }})"
         DESTINATION_DIR="$(dirname "$DESTINATION")"
         echo "$DESTINATION_DIR" >> "$GITHUB_PATH"
 
@@ -122,12 +129,14 @@ runs:
             printf "nfpm is not built for ARM, please build packages on X86, X64, or ARM64 runners" 1>&2
             exit 1
             ;;
+          X86)
+            printf "nfpm is not built for X86, please build packages on X64 or ARM64 runners" 1>&2
+            exit 1
+            ;;
           ARM64)
             ARCH="arm64"
-          X64)
-            ARCH="amd64"
             ;;
-          X86)
+          X64)
             ARCH="x86_64"
             ;;
         esac
@@ -143,11 +152,13 @@ runs:
             ;;
         esac
 
-        mkdir -p tmp
-        gh release download "$VERSION" -p "nfpm_*_${OS}_${ARCH}.tar.gz" -O tmp/nfpm.tgz -R goreleaser/nfpm
-        pushd tmp && tar -xvf nfpm.tgz && popd
-        mv tmp/nfpm/nfpm "$DESTINATION"
-        rm -rf tmp/nfpm
+        mkdir -p tmp/nfpm
+        pushd tmp/nfpm || exit 1
+        gh release download "$VERSION" -p "nfpm_*_${OS}_${ARCH}.tar.gz" -O nfpm.tgz -R goreleaser/nfpm
+        tar -xvf nfpm.tgz
+        mv nfpm "$DESTINATION"
+        popd || exit 1
+        #rm -rf tmp/nfpm
     - name: Check for a Go compiler
       id: check_go
       shell: bash
@@ -162,15 +173,39 @@ runs:
       with:
         cache: false
         go-version-file: go.mod
-    - name: Package rpm
+    - name: Package binary
       shell: bash
+      working-directory: nfpm_packaging
+      env:
+        # These environment variables are used by the template program that generates the nfpm config
+        INPUT_NAME: ${{ inputs.name }}
+        INPUT_ARCH: ${{ inputs.arch }}
+        INPUT_VERSION: ${{ inputs.version }}
+        INPUT_MAINTAINER: ${{ inputs.maintainer }}
+        INPUT_VENDOR: ${{ inputs.vendor }}
+        INPUT_DESCRIPTION: ${{ inputs.description }}
+        INPUT_HOMEPAGE: ${{ inputs.homepage }}
+        INPUT_LICENSE: ${{ inputs.license }}
+        INPUT_DEPENDS: ${{ inputs.depends }}
+        INPUT_BINARY: ${{ inputs.binary }}
+        INPUT_BIN_PATH: ${{ inputs.bin_path }}
+        INPUT_CONFIG_DIR: ${{ inputs.config_dir }}
+        INPUT_PREINSTALL: ${{ inputs.preinstall }}
+        INPUT_POSTINSTALL: ${{ inputs.postinstall }}
+        INPUT_PREREMOVE: ${{ inputs.preremove }}
+        INPUT_POSTREMOVE: ${{ inputs.postremove }}
       run: |
-        INPUT_DEPENDS="${{ inputs.rpm_depends }}" go run . > ./nfpm_rpm_config.yaml
+        if ! fileo=$(file "${{ inputs.binary }}"); then
+          printf "could not find a binary to package"
+          exit 1
+        else
+          printf "packaging binary %s" "$fileo"
+        fi
+        go build -o nfpm_template .
+        INPUT_DEPENDS="${{ inputs.rpm_depends }}" ./nfpm_template > ./nfpm_rpm_config.yml
+        INPUT_DEPENDS="${{ inputs.deb_depends }}" ./nfpm_template > ./nfpm_deb_config.yml
+        cat ./nfpm_*_config.yml
         mkdir -p ./out
-        nfpm package -f ./nfpm_rpm_config.yaml -p rpm -t ./out/
-    - name: Package deb
-      shell: bash
-      run: |
-        INPUT_DEPENDS="${{ inputs.deb_depends }}" go run . > ./nfpm_deb_config.yaml
-        mkdir -p ./out
-        nfpm package -f ./nfpm_deb_config.yaml -p deb -t ./out/
+        nfpm package -f ./nfpm_rpm_config.yml -p rpm -t ./out/
+        nfpm package -f ./nfpm_deb_config.yml -p deb -t ./out/
+        ls -la ./out
